/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCliLoginRouteImport } from './routes/auth/cli-login'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppMembersRouteImport } from './routes/_authed/_app/members'
import { Route as AuthedAppCredentialsRouteImport } from './routes/_authed/_app/credentials'
import { Route as AuthedAppAuditLogRouteImport } from './routes/_authed/_app/audit-log'
import { Route as AuthedAppApiKeysRouteImport } from './routes/_authed/_app/api-keys'
import { Route as AuthedAppAccountRouteImport } from './routes/_authed/_app/account'
import { Route as AuthedAppSettingsIndexRouteImport } from './routes/_authed/_app/settings/index'
import { Route as AuthedAppProjectsIndexRouteImport } from './routes/_authed/_app/projects/index'
import { Route as AuthedAppEnvironmentVariablesIndexRouteImport } from './routes/_authed/_app/environment-variables/index'
import { Route as AuthedAppAppleDevicesIndexRouteImport } from './routes/_authed/_app/apple-devices/index'
import { Route as AuthedAppAccountIndexRouteImport } from './routes/_authed/_app/account/index'
import { Route as AuthedAppProjectsProjectSlugRouteImport } from './routes/_authed/_app/projects/$projectSlug'
import { Route as AuthedAppAccountSessionsRouteImport } from './routes/_authed/_app/account/sessions'
import { Route as AuthedAppAccountProfileRouteImport } from './routes/_authed/_app/account/profile'
import { Route as AuthedAppAccountPasswordRouteImport } from './routes/_authed/_app/account/password'
import { Route as AuthedAppAccountConnectionsRouteImport } from './routes/_authed/_app/account/connections'
import { Route as AuthedAppAccountAppearanceRouteImport } from './routes/_authed/_app/account/appearance'
import { Route as AuthedAppProjectsProjectSlugIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/index'
import { Route as AuthedAppProjectsProjectSlugCredentialsRouteImport } from './routes/_authed/_app/projects/$projectSlug/credentials'
import { Route as AuthedAppProjectsProjectSlugAuditLogRouteImport } from './routes/_authed/_app/projects/$projectSlug/audit-log'
import { Route as AuthedAppProjectsProjectSlugUpdatesIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/updates/index'
import { Route as AuthedAppProjectsProjectSlugSettingsIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/settings/index'
import { Route as AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/environment-variables/index'
import { Route as AuthedAppProjectsProjectSlugChannelsIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/channels/index'
import { Route as AuthedAppProjectsProjectSlugBuildsIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/builds/index'
import { Route as AuthedAppProjectsProjectSlugBranchesIndexRouteImport } from './routes/_authed/_app/projects/$projectSlug/branches/index'
import { Route as AuthedAppProjectsProjectSlugChannelsChannelIdRouteImport } from './routes/_authed/_app/projects/$projectSlug/channels/$channelId'
import { Route as AuthedAppProjectsProjectSlugBuildsBuildIdRouteImport } from './routes/_authed/_app/projects/$projectSlug/builds/$buildId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCliLoginRoute = AuthCliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppMembersRoute = AuthedAppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCredentialsRoute = AuthedAppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAuditLogRoute = AuthedAppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppApiKeysRoute = AuthedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAccountRoute = AuthedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsIndexRoute = AuthedAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProjectsIndexRoute = AuthedAppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppEnvironmentVariablesIndexRoute =
  AuthedAppEnvironmentVariablesIndexRouteImport.update({
    id: '/environment-variables/',
    path: '/environment-variables/',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppAppleDevicesIndexRoute =
  AuthedAppAppleDevicesIndexRouteImport.update({
    id: '/apple-devices/',
    path: '/apple-devices/',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppAccountIndexRoute = AuthedAppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppAccountRoute,
} as any)
const AuthedAppProjectsProjectSlugRoute =
  AuthedAppProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppAccountSessionsRoute =
  AuthedAppAccountSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthedAppAccountRoute,
  } as any)
const AuthedAppAccountProfileRoute = AuthedAppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedAppAccountRoute,
} as any)
const AuthedAppAccountPasswordRoute =
  AuthedAppAccountPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthedAppAccountRoute,
  } as any)
const AuthedAppAccountConnectionsRoute =
  AuthedAppAccountConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthedAppAccountRoute,
  } as any)
const AuthedAppAccountAppearanceRoute =
  AuthedAppAccountAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthedAppAccountRoute,
  } as any)
const AuthedAppProjectsProjectSlugIndexRoute =
  AuthedAppProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugCredentialsRoute =
  AuthedAppProjectsProjectSlugCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugAuditLogRoute =
  AuthedAppProjectsProjectSlugAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugUpdatesIndexRoute =
  AuthedAppProjectsProjectSlugUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugSettingsIndexRoute =
  AuthedAppProjectsProjectSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute =
  AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRouteImport.update({
    id: '/environment-variables/',
    path: '/environment-variables/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugChannelsIndexRoute =
  AuthedAppProjectsProjectSlugChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugBuildsIndexRoute =
  AuthedAppProjectsProjectSlugBuildsIndexRouteImport.update({
    id: '/builds/',
    path: '/builds/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugBranchesIndexRoute =
  AuthedAppProjectsProjectSlugBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugChannelsChannelIdRoute =
  AuthedAppProjectsProjectSlugChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)
const AuthedAppProjectsProjectSlugBuildsBuildIdRoute =
  AuthedAppProjectsProjectSlugBuildsBuildIdRouteImport.update({
    id: '/builds/$buildId',
    path: '/builds/$buildId',
    getParentRoute: () => AuthedAppProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/auth/cli-login': typeof AuthCliLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/account': typeof AuthedAppAccountRouteWithChildren
  '/api-keys': typeof AuthedAppApiKeysRoute
  '/audit-log': typeof AuthedAppAuditLogRoute
  '/credentials': typeof AuthedAppCredentialsRoute
  '/members': typeof AuthedAppMembersRoute
  '/account/appearance': typeof AuthedAppAccountAppearanceRoute
  '/account/connections': typeof AuthedAppAccountConnectionsRoute
  '/account/password': typeof AuthedAppAccountPasswordRoute
  '/account/profile': typeof AuthedAppAccountProfileRoute
  '/account/sessions': typeof AuthedAppAccountSessionsRoute
  '/projects/$projectSlug': typeof AuthedAppProjectsProjectSlugRouteWithChildren
  '/account/': typeof AuthedAppAccountIndexRoute
  '/apple-devices/': typeof AuthedAppAppleDevicesIndexRoute
  '/environment-variables/': typeof AuthedAppEnvironmentVariablesIndexRoute
  '/projects/': typeof AuthedAppProjectsIndexRoute
  '/settings/': typeof AuthedAppSettingsIndexRoute
  '/projects/$projectSlug/audit-log': typeof AuthedAppProjectsProjectSlugAuditLogRoute
  '/projects/$projectSlug/credentials': typeof AuthedAppProjectsProjectSlugCredentialsRoute
  '/projects/$projectSlug/': typeof AuthedAppProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/builds/$buildId': typeof AuthedAppProjectsProjectSlugBuildsBuildIdRoute
  '/projects/$projectSlug/channels/$channelId': typeof AuthedAppProjectsProjectSlugChannelsChannelIdRoute
  '/projects/$projectSlug/branches/': typeof AuthedAppProjectsProjectSlugBranchesIndexRoute
  '/projects/$projectSlug/builds/': typeof AuthedAppProjectsProjectSlugBuildsIndexRoute
  '/projects/$projectSlug/channels/': typeof AuthedAppProjectsProjectSlugChannelsIndexRoute
  '/projects/$projectSlug/environment-variables/': typeof AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute
  '/projects/$projectSlug/settings/': typeof AuthedAppProjectsProjectSlugSettingsIndexRoute
  '/projects/$projectSlug/updates/': typeof AuthedAppProjectsProjectSlugUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/auth/cli-login': typeof AuthCliLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/api-keys': typeof AuthedAppApiKeysRoute
  '/audit-log': typeof AuthedAppAuditLogRoute
  '/credentials': typeof AuthedAppCredentialsRoute
  '/members': typeof AuthedAppMembersRoute
  '/account/appearance': typeof AuthedAppAccountAppearanceRoute
  '/account/connections': typeof AuthedAppAccountConnectionsRoute
  '/account/password': typeof AuthedAppAccountPasswordRoute
  '/account/profile': typeof AuthedAppAccountProfileRoute
  '/account/sessions': typeof AuthedAppAccountSessionsRoute
  '/account': typeof AuthedAppAccountIndexRoute
  '/apple-devices': typeof AuthedAppAppleDevicesIndexRoute
  '/environment-variables': typeof AuthedAppEnvironmentVariablesIndexRoute
  '/projects': typeof AuthedAppProjectsIndexRoute
  '/settings': typeof AuthedAppSettingsIndexRoute
  '/projects/$projectSlug/audit-log': typeof AuthedAppProjectsProjectSlugAuditLogRoute
  '/projects/$projectSlug/credentials': typeof AuthedAppProjectsProjectSlugCredentialsRoute
  '/projects/$projectSlug': typeof AuthedAppProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/builds/$buildId': typeof AuthedAppProjectsProjectSlugBuildsBuildIdRoute
  '/projects/$projectSlug/channels/$channelId': typeof AuthedAppProjectsProjectSlugChannelsChannelIdRoute
  '/projects/$projectSlug/branches': typeof AuthedAppProjectsProjectSlugBranchesIndexRoute
  '/projects/$projectSlug/builds': typeof AuthedAppProjectsProjectSlugBuildsIndexRoute
  '/projects/$projectSlug/channels': typeof AuthedAppProjectsProjectSlugChannelsIndexRoute
  '/projects/$projectSlug/environment-variables': typeof AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute
  '/projects/$projectSlug/settings': typeof AuthedAppProjectsProjectSlugSettingsIndexRoute
  '/projects/$projectSlug/updates': typeof AuthedAppProjectsProjectSlugUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/auth/cli-login': typeof AuthCliLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authed/_app/account': typeof AuthedAppAccountRouteWithChildren
  '/_authed/_app/api-keys': typeof AuthedAppApiKeysRoute
  '/_authed/_app/audit-log': typeof AuthedAppAuditLogRoute
  '/_authed/_app/credentials': typeof AuthedAppCredentialsRoute
  '/_authed/_app/members': typeof AuthedAppMembersRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/_app/account/appearance': typeof AuthedAppAccountAppearanceRoute
  '/_authed/_app/account/connections': typeof AuthedAppAccountConnectionsRoute
  '/_authed/_app/account/password': typeof AuthedAppAccountPasswordRoute
  '/_authed/_app/account/profile': typeof AuthedAppAccountProfileRoute
  '/_authed/_app/account/sessions': typeof AuthedAppAccountSessionsRoute
  '/_authed/_app/projects/$projectSlug': typeof AuthedAppProjectsProjectSlugRouteWithChildren
  '/_authed/_app/account/': typeof AuthedAppAccountIndexRoute
  '/_authed/_app/apple-devices/': typeof AuthedAppAppleDevicesIndexRoute
  '/_authed/_app/environment-variables/': typeof AuthedAppEnvironmentVariablesIndexRoute
  '/_authed/_app/projects/': typeof AuthedAppProjectsIndexRoute
  '/_authed/_app/settings/': typeof AuthedAppSettingsIndexRoute
  '/_authed/_app/projects/$projectSlug/audit-log': typeof AuthedAppProjectsProjectSlugAuditLogRoute
  '/_authed/_app/projects/$projectSlug/credentials': typeof AuthedAppProjectsProjectSlugCredentialsRoute
  '/_authed/_app/projects/$projectSlug/': typeof AuthedAppProjectsProjectSlugIndexRoute
  '/_authed/_app/projects/$projectSlug/builds/$buildId': typeof AuthedAppProjectsProjectSlugBuildsBuildIdRoute
  '/_authed/_app/projects/$projectSlug/channels/$channelId': typeof AuthedAppProjectsProjectSlugChannelsChannelIdRoute
  '/_authed/_app/projects/$projectSlug/branches/': typeof AuthedAppProjectsProjectSlugBranchesIndexRoute
  '/_authed/_app/projects/$projectSlug/builds/': typeof AuthedAppProjectsProjectSlugBuildsIndexRoute
  '/_authed/_app/projects/$projectSlug/channels/': typeof AuthedAppProjectsProjectSlugChannelsIndexRoute
  '/_authed/_app/projects/$projectSlug/environment-variables/': typeof AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute
  '/_authed/_app/projects/$projectSlug/settings/': typeof AuthedAppProjectsProjectSlugSettingsIndexRoute
  '/_authed/_app/projects/$projectSlug/updates/': typeof AuthedAppProjectsProjectSlugUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/onboarding'
    | '/auth/cli-login'
    | '/auth/login'
    | '/account'
    | '/api-keys'
    | '/audit-log'
    | '/credentials'
    | '/members'
    | '/account/appearance'
    | '/account/connections'
    | '/account/password'
    | '/account/profile'
    | '/account/sessions'
    | '/projects/$projectSlug'
    | '/account/'
    | '/apple-devices/'
    | '/environment-variables/'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectSlug/audit-log'
    | '/projects/$projectSlug/credentials'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/builds/$buildId'
    | '/projects/$projectSlug/channels/$channelId'
    | '/projects/$projectSlug/branches/'
    | '/projects/$projectSlug/builds/'
    | '/projects/$projectSlug/channels/'
    | '/projects/$projectSlug/environment-variables/'
    | '/projects/$projectSlug/settings/'
    | '/projects/$projectSlug/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/onboarding'
    | '/auth/cli-login'
    | '/auth/login'
    | '/api-keys'
    | '/audit-log'
    | '/credentials'
    | '/members'
    | '/account/appearance'
    | '/account/connections'
    | '/account/password'
    | '/account/profile'
    | '/account/sessions'
    | '/account'
    | '/apple-devices'
    | '/environment-variables'
    | '/projects'
    | '/settings'
    | '/projects/$projectSlug/audit-log'
    | '/projects/$projectSlug/credentials'
    | '/projects/$projectSlug'
    | '/projects/$projectSlug/builds/$buildId'
    | '/projects/$projectSlug/channels/$channelId'
    | '/projects/$projectSlug/branches'
    | '/projects/$projectSlug/builds'
    | '/projects/$projectSlug/channels'
    | '/projects/$projectSlug/environment-variables'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/updates'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invitation'
    | '/auth'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/auth/cli-login'
    | '/auth/login'
    | '/_authed/_app/account'
    | '/_authed/_app/api-keys'
    | '/_authed/_app/audit-log'
    | '/_authed/_app/credentials'
    | '/_authed/_app/members'
    | '/_authed/_app/'
    | '/_authed/_app/account/appearance'
    | '/_authed/_app/account/connections'
    | '/_authed/_app/account/password'
    | '/_authed/_app/account/profile'
    | '/_authed/_app/account/sessions'
    | '/_authed/_app/projects/$projectSlug'
    | '/_authed/_app/account/'
    | '/_authed/_app/apple-devices/'
    | '/_authed/_app/environment-variables/'
    | '/_authed/_app/projects/'
    | '/_authed/_app/settings/'
    | '/_authed/_app/projects/$projectSlug/audit-log'
    | '/_authed/_app/projects/$projectSlug/credentials'
    | '/_authed/_app/projects/$projectSlug/'
    | '/_authed/_app/projects/$projectSlug/builds/$buildId'
    | '/_authed/_app/projects/$projectSlug/channels/$channelId'
    | '/_authed/_app/projects/$projectSlug/branches/'
    | '/_authed/_app/projects/$projectSlug/builds/'
    | '/_authed/_app/projects/$projectSlug/channels/'
    | '/_authed/_app/projects/$projectSlug/environment-variables/'
    | '/_authed/_app/projects/$projectSlug/settings/'
    | '/_authed/_app/projects/$projectSlug/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/cli-login': {
      id: '/auth/cli-login'
      path: '/cli-login'
      fullPath: '/auth/cli-login'
      preLoaderRoute: typeof AuthCliLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/members': {
      id: '/_authed/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedAppMembersRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/credentials': {
      id: '/_authed/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthedAppCredentialsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/audit-log': {
      id: '/_authed/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthedAppAuditLogRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/api-keys': {
      id: '/_authed/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedAppApiKeysRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/account': {
      id: '/_authed/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAppAccountRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings/': {
      id: '/_authed/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedAppSettingsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/projects/': {
      id: '/_authed/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedAppProjectsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/environment-variables/': {
      id: '/_authed/_app/environment-variables/'
      path: '/environment-variables'
      fullPath: '/environment-variables/'
      preLoaderRoute: typeof AuthedAppEnvironmentVariablesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/apple-devices/': {
      id: '/_authed/_app/apple-devices/'
      path: '/apple-devices'
      fullPath: '/apple-devices/'
      preLoaderRoute: typeof AuthedAppAppleDevicesIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/account/': {
      id: '/_authed/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAppAccountIndexRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/projects/$projectSlug': {
      id: '/_authed/_app/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/account/sessions': {
      id: '/_authed/_app/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AuthedAppAccountSessionsRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/account/profile': {
      id: '/_authed/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthedAppAccountProfileRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/account/password': {
      id: '/_authed/_app/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthedAppAccountPasswordRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/account/connections': {
      id: '/_authed/_app/account/connections'
      path: '/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AuthedAppAccountConnectionsRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/account/appearance': {
      id: '/_authed/_app/account/appearance'
      path: '/appearance'
      fullPath: '/account/appearance'
      preLoaderRoute: typeof AuthedAppAccountAppearanceRouteImport
      parentRoute: typeof AuthedAppAccountRoute
    }
    '/_authed/_app/projects/$projectSlug/': {
      id: '/_authed/_app/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/credentials': {
      id: '/_authed/_app/projects/$projectSlug/credentials'
      path: '/credentials'
      fullPath: '/projects/$projectSlug/credentials'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugCredentialsRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/audit-log': {
      id: '/_authed/_app/projects/$projectSlug/audit-log'
      path: '/audit-log'
      fullPath: '/projects/$projectSlug/audit-log'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugAuditLogRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/updates/': {
      id: '/_authed/_app/projects/$projectSlug/updates/'
      path: '/updates'
      fullPath: '/projects/$projectSlug/updates/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugUpdatesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/settings/': {
      id: '/_authed/_app/projects/$projectSlug/settings/'
      path: '/settings'
      fullPath: '/projects/$projectSlug/settings/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/environment-variables/': {
      id: '/_authed/_app/projects/$projectSlug/environment-variables/'
      path: '/environment-variables'
      fullPath: '/projects/$projectSlug/environment-variables/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/channels/': {
      id: '/_authed/_app/projects/$projectSlug/channels/'
      path: '/channels'
      fullPath: '/projects/$projectSlug/channels/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugChannelsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/builds/': {
      id: '/_authed/_app/projects/$projectSlug/builds/'
      path: '/builds'
      fullPath: '/projects/$projectSlug/builds/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugBuildsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/branches/': {
      id: '/_authed/_app/projects/$projectSlug/branches/'
      path: '/branches'
      fullPath: '/projects/$projectSlug/branches/'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugBranchesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/channels/$channelId': {
      id: '/_authed/_app/projects/$projectSlug/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/projects/$projectSlug/channels/$channelId'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugChannelsChannelIdRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
    '/_authed/_app/projects/$projectSlug/builds/$buildId': {
      id: '/_authed/_app/projects/$projectSlug/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/projects/$projectSlug/builds/$buildId'
      preLoaderRoute: typeof AuthedAppProjectsProjectSlugBuildsBuildIdRouteImport
      parentRoute: typeof AuthedAppProjectsProjectSlugRoute
    }
  }
}

interface AuthedAppAccountRouteChildren {
  AuthedAppAccountAppearanceRoute: typeof AuthedAppAccountAppearanceRoute
  AuthedAppAccountConnectionsRoute: typeof AuthedAppAccountConnectionsRoute
  AuthedAppAccountPasswordRoute: typeof AuthedAppAccountPasswordRoute
  AuthedAppAccountProfileRoute: typeof AuthedAppAccountProfileRoute
  AuthedAppAccountSessionsRoute: typeof AuthedAppAccountSessionsRoute
  AuthedAppAccountIndexRoute: typeof AuthedAppAccountIndexRoute
}

const AuthedAppAccountRouteChildren: AuthedAppAccountRouteChildren = {
  AuthedAppAccountAppearanceRoute: AuthedAppAccountAppearanceRoute,
  AuthedAppAccountConnectionsRoute: AuthedAppAccountConnectionsRoute,
  AuthedAppAccountPasswordRoute: AuthedAppAccountPasswordRoute,
  AuthedAppAccountProfileRoute: AuthedAppAccountProfileRoute,
  AuthedAppAccountSessionsRoute: AuthedAppAccountSessionsRoute,
  AuthedAppAccountIndexRoute: AuthedAppAccountIndexRoute,
}

const AuthedAppAccountRouteWithChildren =
  AuthedAppAccountRoute._addFileChildren(AuthedAppAccountRouteChildren)

interface AuthedAppProjectsProjectSlugRouteChildren {
  AuthedAppProjectsProjectSlugAuditLogRoute: typeof AuthedAppProjectsProjectSlugAuditLogRoute
  AuthedAppProjectsProjectSlugCredentialsRoute: typeof AuthedAppProjectsProjectSlugCredentialsRoute
  AuthedAppProjectsProjectSlugIndexRoute: typeof AuthedAppProjectsProjectSlugIndexRoute
  AuthedAppProjectsProjectSlugBuildsBuildIdRoute: typeof AuthedAppProjectsProjectSlugBuildsBuildIdRoute
  AuthedAppProjectsProjectSlugChannelsChannelIdRoute: typeof AuthedAppProjectsProjectSlugChannelsChannelIdRoute
  AuthedAppProjectsProjectSlugBranchesIndexRoute: typeof AuthedAppProjectsProjectSlugBranchesIndexRoute
  AuthedAppProjectsProjectSlugBuildsIndexRoute: typeof AuthedAppProjectsProjectSlugBuildsIndexRoute
  AuthedAppProjectsProjectSlugChannelsIndexRoute: typeof AuthedAppProjectsProjectSlugChannelsIndexRoute
  AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute: typeof AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute
  AuthedAppProjectsProjectSlugSettingsIndexRoute: typeof AuthedAppProjectsProjectSlugSettingsIndexRoute
  AuthedAppProjectsProjectSlugUpdatesIndexRoute: typeof AuthedAppProjectsProjectSlugUpdatesIndexRoute
}

const AuthedAppProjectsProjectSlugRouteChildren: AuthedAppProjectsProjectSlugRouteChildren =
  {
    AuthedAppProjectsProjectSlugAuditLogRoute:
      AuthedAppProjectsProjectSlugAuditLogRoute,
    AuthedAppProjectsProjectSlugCredentialsRoute:
      AuthedAppProjectsProjectSlugCredentialsRoute,
    AuthedAppProjectsProjectSlugIndexRoute:
      AuthedAppProjectsProjectSlugIndexRoute,
    AuthedAppProjectsProjectSlugBuildsBuildIdRoute:
      AuthedAppProjectsProjectSlugBuildsBuildIdRoute,
    AuthedAppProjectsProjectSlugChannelsChannelIdRoute:
      AuthedAppProjectsProjectSlugChannelsChannelIdRoute,
    AuthedAppProjectsProjectSlugBranchesIndexRoute:
      AuthedAppProjectsProjectSlugBranchesIndexRoute,
    AuthedAppProjectsProjectSlugBuildsIndexRoute:
      AuthedAppProjectsProjectSlugBuildsIndexRoute,
    AuthedAppProjectsProjectSlugChannelsIndexRoute:
      AuthedAppProjectsProjectSlugChannelsIndexRoute,
    AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute:
      AuthedAppProjectsProjectSlugEnvironmentVariablesIndexRoute,
    AuthedAppProjectsProjectSlugSettingsIndexRoute:
      AuthedAppProjectsProjectSlugSettingsIndexRoute,
    AuthedAppProjectsProjectSlugUpdatesIndexRoute:
      AuthedAppProjectsProjectSlugUpdatesIndexRoute,
  }

const AuthedAppProjectsProjectSlugRouteWithChildren =
  AuthedAppProjectsProjectSlugRoute._addFileChildren(
    AuthedAppProjectsProjectSlugRouteChildren,
  )

interface AuthedAppRouteChildren {
  AuthedAppAccountRoute: typeof AuthedAppAccountRouteWithChildren
  AuthedAppApiKeysRoute: typeof AuthedAppApiKeysRoute
  AuthedAppAuditLogRoute: typeof AuthedAppAuditLogRoute
  AuthedAppCredentialsRoute: typeof AuthedAppCredentialsRoute
  AuthedAppMembersRoute: typeof AuthedAppMembersRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppProjectsProjectSlugRoute: typeof AuthedAppProjectsProjectSlugRouteWithChildren
  AuthedAppAppleDevicesIndexRoute: typeof AuthedAppAppleDevicesIndexRoute
  AuthedAppEnvironmentVariablesIndexRoute: typeof AuthedAppEnvironmentVariablesIndexRoute
  AuthedAppProjectsIndexRoute: typeof AuthedAppProjectsIndexRoute
  AuthedAppSettingsIndexRoute: typeof AuthedAppSettingsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppAccountRoute: AuthedAppAccountRouteWithChildren,
  AuthedAppApiKeysRoute: AuthedAppApiKeysRoute,
  AuthedAppAuditLogRoute: AuthedAppAuditLogRoute,
  AuthedAppCredentialsRoute: AuthedAppCredentialsRoute,
  AuthedAppMembersRoute: AuthedAppMembersRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppProjectsProjectSlugRoute:
    AuthedAppProjectsProjectSlugRouteWithChildren,
  AuthedAppAppleDevicesIndexRoute: AuthedAppAppleDevicesIndexRoute,
  AuthedAppEnvironmentVariablesIndexRoute:
    AuthedAppEnvironmentVariablesIndexRoute,
  AuthedAppProjectsIndexRoute: AuthedAppProjectsIndexRoute,
  AuthedAppSettingsIndexRoute: AuthedAppSettingsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthCliLoginRoute: typeof AuthCliLoginRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCliLoginRoute: AuthCliLoginRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
