/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  access_token: string | null;
  access_token_expires_at: string | null;
  account_id: string;
  created_at: string;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: string | null;
  scope: string | null;
  updated_at: string;
  user_id: string;
}

export interface AndroidApplicationIdentifiers {
  created_at: Generated<string>;
  id: string | null;
  organization_id: string;
  package_name: string;
  project_id: string;
  updated_at: Generated<string>;
}

export interface AndroidBuildCredentials {
  android_application_identifier_id: string;
  android_upload_keystore_id: string | null;
  created_at: Generated<string>;
  google_service_account_key_for_fcm_v1_id: string | null;
  google_service_account_key_for_submissions_id: string | null;
  id: string | null;
  is_default: Generated<number>;
  name: string;
  organization_id: string;
  updated_at: Generated<string>;
}

export interface AndroidUploadKeystores {
  created_at: Generated<string>;
  id: string | null;
  key_alias: string;
  keystore_type: string | null;
  md5_fingerprint: string | null;
  organization_id: string;
  r2_key: string;
  sha1_fingerprint: string | null;
  sha256_fingerprint: string | null;
  updated_at: Generated<string>;
  vault_version: number;
  wrapped_dek: string;
}

export interface Apikey {
  config_id: string;
  created_at: string;
  enabled: number | null;
  expires_at: string | null;
  id: string;
  key: string;
  last_refill_at: string | null;
  last_request: string | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rate_limit_enabled: number | null;
  rate_limit_max: number | null;
  rate_limit_time_window: number | null;
  reference_id: string;
  refill_amount: number | null;
  refill_interval: number | null;
  remaining: number | null;
  request_count: number | null;
  start: string | null;
  updated_at: string;
}

export interface AppleDistributionCertificates {
  apple_team_id: string;
  created_at: Generated<string>;
  developer_id_identifier: string | null;
  id: string | null;
  organization_id: string;
  r2_key: string;
  serial_number: string;
  updated_at: Generated<string>;
  valid_from: string;
  valid_until: string;
  vault_version: number;
  wrapped_dek: string;
}

export interface AppleProvisioningProfiles {
  apple_distribution_certificate_id: string | null;
  apple_team_id: string;
  bundle_identifier: string;
  created_at: Generated<string>;
  developer_portal_identifier: string | null;
  device_roster_hash: string | null;
  distribution_type: string;
  id: string | null;
  is_managed: Generated<number>;
  organization_id: string;
  profile_name: string | null;
  r2_key: string;
  updated_at: Generated<string>;
  valid_until: string | null;
}

export interface ApplePushKeys {
  apple_team_id: string;
  created_at: Generated<string>;
  id: string | null;
  key_id: string;
  organization_id: string;
  r2_key: string;
  updated_at: Generated<string>;
  vault_version: number;
  wrapped_dek: string;
}

export interface AppleTeams {
  apple_team_id: string;
  apple_team_type: string;
  created_at: Generated<string>;
  id: string | null;
  name: string | null;
  organization_id: string;
  updated_at: Generated<string>;
}

export interface AscApiKeys {
  apple_team_id: string | null;
  created_at: Generated<string>;
  id: string | null;
  issuer_id: Generated<string>;
  key_id: string;
  name: string;
  organization_id: string;
  r2_key: string;
  roles: Generated<string>;
  updated_at: Generated<string>;
  vault_version: number;
  wrapped_dek: string;
}

export interface Assets {
  byte_size: number;
  content_checksum: Generated<string>;
  content_type: string;
  created_at: string;
  file_ext: string;
  hash: string;
  r2_key: string;
}

export interface AuditLogs {
  action: string;
  actor_email: string;
  actor_id: string | null;
  created_at: Generated<string>;
  id: string | null;
  metadata: string | null;
  organization_id: string;
  project_id: string | null;
  resource_id: string | null;
  resource_type: string;
  source: string;
}

export interface Branches {
  created_at: string;
  id: string;
  is_builtin: Generated<number>;
  name: string;
  project_id: string;
}

export interface BuildArtifacts {
  build_id: string | null;
  byte_size: number;
  content_type: Generated<string>;
  created_at: Generated<string>;
  format: string;
  r2_key: string;
  sha256: string;
}

export interface Builds {
  app_version: string | null;
  build_number: string | null;
  bundle_id: string | null;
  created_at: Generated<string>;
  distribution: string;
  fingerprint_hash: string | null;
  git_commit: string | null;
  git_dirty: Generated<number>;
  git_ref: string | null;
  id: string | null;
  message: string | null;
  metadata_json: Generated<string>;
  platform: string;
  profile: Generated<string>;
  project_id: string;
  runtime_version: string | null;
}

export interface Channels {
  branch_id: string;
  branch_mapping_json: string | null;
  cache_version: Generated<number>;
  created_at: string;
  id: string;
  is_builtin: Generated<number>;
  is_paused: Generated<number>;
  name: string;
  project_id: string;
}

export interface DeviceRegistrationRequests {
  apple_team_id: string | null;
  consumed_at: string | null;
  consumed_device_id: string | null;
  created_at: Generated<string>;
  created_by_user_id: string;
  device_class_hint: string | null;
  device_name_hint: string | null;
  expires_at: string;
  id: string | null;
  organization_id: string;
}

export interface Devices {
  apple_device_portal_id: string | null;
  apple_team_id: string | null;
  created_at: Generated<string>;
  device_class: string;
  enabled: Generated<number>;
  id: string | null;
  identifier: string;
  model: string | null;
  name: string;
  organization_id: string;
  updated_at: Generated<string>;
}

export interface DevicesFts {
  device_id: string | null;
  identifier: string | null;
  name: string | null;
  organization_id: string | null;
}

export interface Environments {
  created_at: Generated<string>;
  id: string;
  name: string;
  organization_id: string;
}

export interface EnvVarRevisions {
  created_at: Generated<string>;
  created_by_user_id: string | null;
  env_var_id: string;
  id: string | null;
  organization_id: string;
  revision_number: number;
  updated_at: Generated<string>;
  value_ciphertext: string;
  vault_version: number;
  wrapped_dek: string;
}

export interface EnvVars {
  created_at: Generated<string>;
  current_revision_id: string | null;
  environment: string;
  id: string | null;
  key: string;
  organization_id: string;
  project_id: string | null;
  scope: string;
  updated_at: Generated<string>;
  visibility: string;
}

export interface GoogleServiceAccountKeys {
  client_email: string;
  client_id: string | null;
  created_at: Generated<string>;
  google_project_id: string;
  id: string | null;
  organization_id: string;
  private_key_id: string;
  r2_key: string;
  updated_at: Generated<string>;
  vault_version: number;
  wrapped_dek: string;
}

export interface IamGroup {
  created_at: Generated<string>;
  description: string | null;
  id: string;
  name: string;
  organization_id: string;
  updated_at: string | null;
}

export interface IamGroupMembership {
  created_at: Generated<string>;
  group_id: string;
  member_id: string;
}

export interface Invitation {
  created_at: string;
  email: string;
  expires_at: string;
  id: string;
  inviter_id: string;
  organization_id: string;
  role: string | null;
  status: string;
}

export interface IosAppMetadata {
  app_name: string | null;
  asc_app_id: string | null;
  bundle_identifier: string;
  company_name: string | null;
  created_at: Generated<string>;
  id: string | null;
  language: Generated<string>;
  organization_id: string;
  project_id: string;
  sku: string | null;
  updated_at: Generated<string>;
}

export interface IosBundleConfigurations {
  apple_distribution_certificate_id: string | null;
  apple_provisioning_profile_id: string | null;
  apple_push_key_id: string | null;
  apple_team_id: string;
  asc_api_key_id: string | null;
  bundle_identifier: string;
  created_at: Generated<string>;
  distribution_type: string;
  id: string | null;
  organization_id: string;
  parent_bundle_identifier: string | null;
  project_id: string;
  target_name: string | null;
  updated_at: Generated<string>;
}

export interface Member {
  created_at: string;
  id: string;
  organization_id: string;
  role: string;
  user_id: string;
}

export interface Organization {
  created_at: string;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface OrgVaultKeyWraps {
  created_at: Generated<string>;
  organization_id: string;
  user_encryption_key_id: string;
  vault_version: number;
  wrapped_key: string;
}

export interface OrgVaults {
  created_at: Generated<string>;
  organization_id: string | null;
  rotation_pending: Generated<number>;
  rotation_pending_reason: string | null;
  rotation_pending_since: string | null;
  updated_at: Generated<string>;
  vault_version: Generated<number>;
}

export interface Policy {
  created_at: Generated<string>;
  description: string | null;
  document: string;
  id: string;
  name: string;
  organization_id: string;
  updated_at: string | null;
}

export interface PolicyAttachment {
  created_at: Generated<string>;
  id: string;
  organization_id: string;
  policy_id: string;
  principal_id: string;
  principal_type: string;
}

export interface ProjectProtocolMetadata {
  manifest_filters_json: string | null;
  project_id: string;
  scope_key: string;
  server_defined_headers_json: string | null;
  updated_at: Generated<string>;
}

export interface Projects {
  created_at: string;
  id: string;
  last_activity_at: string | null;
  name: string;
  organization_id: string;
  scope_key: string | null;
  slug: string;
}

export interface ProjectsFts {
  name: string | null;
  organization_id: string | null;
  project_id: string | null;
  slug: string | null;
}

export interface Session {
  active_organization_id: string | null;
  created_at: string;
  expires_at: string;
  id: string;
  impersonated_by: string | null;
  ip_address: string | null;
  token: string;
  updated_at: string;
  user_agent: string | null;
  user_id: string;
}

export interface Submissions {
  archive_source: string;
  archive_url: string | null;
  build_id: string | null;
  completed_at: string | null;
  created_at: Generated<string>;
  error_code: string | null;
  error_message: string | null;
  id: string | null;
  initiating_user_id: string | null;
  log_files: Generated<string>;
  organization_id: string;
  platform: string;
  profile_name: Generated<string>;
  project_id: string;
  queued_at: string | null;
  started_at: string | null;
  status: string;
  submission_config: Generated<string>;
  updated_at: Generated<string>;
}

export interface UpdateAssets {
  asset_hash: string;
  asset_key: string;
  is_launch: Generated<number>;
  update_id: string;
}

export interface Updates {
  branch_id: string;
  certificate_chain: string | null;
  created_at: string;
  directive_body: string | null;
  extra_json: string | null;
  fingerprint_hash: string | null;
  git_commit: string | null;
  git_dirty: Generated<number>;
  group_id: string;
  id: string;
  is_embedded: Generated<number>;
  is_rollback: Generated<number>;
  manifest_body: string | null;
  message: string;
  metadata_json: Generated<string>;
  platform: string;
  rollout_percentage: Generated<number>;
  runtime_version: string;
  signature: string | null;
}

export interface User {
  approved: Generated<number>;
  ban_expires: string | null;
  ban_reason: string | null;
  banned: number | null;
  created_at: string;
  email: string;
  email_verified: number;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updated_at: string;
}

export interface UserEncryptionKeys {
  created_at: Generated<string>;
  fingerprint: string;
  id: string | null;
  kind: string;
  label: string;
  last_used_at: string | null;
  organization_id: string | null;
  public_key: string;
  revoked_at: string | null;
  user_id: string | null;
}

export interface Verification {
  created_at: string;
  expires_at: string;
  id: string;
  identifier: string;
  updated_at: string;
  value: string;
}

export interface Webhooks {
  created_at: string;
  enabled: Generated<number>;
  events: Generated<string>;
  id: string;
  name: string;
  organization_id: string;
  project_id: string | null;
  secret: string;
  updated_at: string;
  url: string;
}

export interface DB {
  account: Account;
  android_application_identifiers: AndroidApplicationIdentifiers;
  android_build_credentials: AndroidBuildCredentials;
  android_upload_keystores: AndroidUploadKeystores;
  apikey: Apikey;
  apple_distribution_certificates: AppleDistributionCertificates;
  apple_provisioning_profiles: AppleProvisioningProfiles;
  apple_push_keys: ApplePushKeys;
  apple_teams: AppleTeams;
  asc_api_keys: AscApiKeys;
  assets: Assets;
  audit_logs: AuditLogs;
  branches: Branches;
  build_artifacts: BuildArtifacts;
  builds: Builds;
  channels: Channels;
  device_registration_requests: DeviceRegistrationRequests;
  devices: Devices;
  devices_fts: DevicesFts;
  env_var_revisions: EnvVarRevisions;
  env_vars: EnvVars;
  environments: Environments;
  google_service_account_keys: GoogleServiceAccountKeys;
  iam_group: IamGroup;
  iam_group_membership: IamGroupMembership;
  invitation: Invitation;
  ios_app_metadata: IosAppMetadata;
  ios_bundle_configurations: IosBundleConfigurations;
  member: Member;
  org_vault_key_wraps: OrgVaultKeyWraps;
  org_vaults: OrgVaults;
  organization: Organization;
  policy: Policy;
  policy_attachment: PolicyAttachment;
  project_protocol_metadata: ProjectProtocolMetadata;
  projects: Projects;
  projects_fts: ProjectsFts;
  session: Session;
  submissions: Submissions;
  update_assets: UpdateAssets;
  updates: Updates;
  user: User;
  user_encryption_keys: UserEncryptionKeys;
  verification: Verification;
  webhooks: Webhooks;
}
