/**
 * Pure helpers describing the classic bsdiff-4.x (BSDIFF40) patch envelope that
 * `@better-update/bsdiff` (via the qbsdiff crate) produces and that
 * expo-updates 56's vendored `bspatch.c` hard-checks with `memcmp(.., "BSDIFF40", 8)`.
 *
 * This is the only hand-written JS in the package — the native binding's loader
 * (`index.js`) and types (`index.d.ts`) are auto-generated by `napi build`.
 */

/** First 8 bytes of every classic bsdiff-4.x patch. */
export const BSDIFF40_MAGIC = "BSDIFF40";

/**
 * Pure check that a produced patch's leading bytes are the BSDIFF40 magic the
 * on-device bspatch hard-checks. A mismatch means the patch would fail to
 * apply, so a caller should refuse to ship it. Reads the first 8 bytes as
 * latin1 so each byte maps 1:1 to a character.
 */
export const hasBsdiff40Magic = (leadingBytes: Uint8Array): boolean =>
  Buffer.from(leadingBytes.subarray(0, BSDIFF40_MAGIC.length)).toString("latin1") ===
  BSDIFF40_MAGIC;
